// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM8yKVQojkLvJ2ozjbSgRVIwZ_r24VrUQ',
    appId: '1:162832384771:web:8717264d75640a0a799f36',
    messagingSenderId: '162832384771',
    projectId: 'smartbyahe',
    authDomain: 'smartbyahe.firebaseapp.com',
    storageBucket: 'smartbyahe.firebasestorage.app',
    measurementId: 'G-80ST9ZYHLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9sAATa_1uz3jbbngKtYUTTdtWyF1jn_c',
    appId: '1:162832384771:android:46322ee7e91c3048799f36',
    messagingSenderId: '162832384771',
    projectId: 'smartbyahe',
    storageBucket: 'smartbyahe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbVxlI_pQHBX1WELNzDWzAUWyq02_ORFs',
    appId: '1:162832384771:ios:5af0761de927b34d799f36',
    messagingSenderId: '162832384771',
    projectId: 'smartbyahe',
    storageBucket: 'smartbyahe.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

}